### ISSUE TITLE
Document behavior of NPMRelease Job if the package fails to build

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade-utils#48]
I don't know exactly the behaviour of `npm publish` if the package fails to build - this is irrelevant in how _we_ use this job, since we always build _and test_ before publishing, but it might be worth investigating and adding a note in the readme for users.

_Originally posted by @radu-matei in https://github.com/brigadecore/brigade-utils/pull/45_

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
