### ISSUE TITLE
Ensure this can be imported in a brigade.js file

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade-utils#7]

**Comment by vdice** [comment]
Excited to revisit this effort!  It would be so great to start using the utilities in this repo, to DRY up existing `brigade.js` files but most importantly, lower the barrier of entry for first-time authors.  I bet we have a bunch that we can add here as well, once its use is vetted and documented.

Let's work together to make this happen.

**Comment by radu-matei** [comment]
See readme - https://github.com/brigadecore/brigade-utils/blob/master/readme.md
